使用设备: cuda
训练集加载完成，共有 4000 个样本。
验证集加载完成，共有 32000 个样本。
tokenizer.json: 100%|███████████████████████████████████████████████████████████████████████████████████| 1.36M/1.36M [00:00<00:00, 1.84MB/s]
config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 665/665 [00:00<00:00, 2.32MB/s]
添加了填充标记 '[PAD]' 到分词器。
Traceback (most recent call last):
  File "/mnt/file2/changye/NLPFINAL/fine-tuning/main.py", line 175, in <module>
    main(args)
  File "/mnt/file2/changye/NLPFINAL/fine-tuning/main.py", line 94, in main
    tokenized_train = prepare_dataset(train_dataset, tokenizer, max_length=args.max_length)
  File "/mnt/file2/changye/NLPFINAL/fine-tuning/supervised_dataset.py", line 98, in prepare_dataset
    remove_columns=dataset['train'].column_names
  File "/home/changye/miniconda3/envs/ML/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2872, in __getitem__
    return self._getitem(key)
  File "/home/changye/miniconda3/envs/ML/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2856, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices)
  File "/home/changye/miniconda3/envs/ML/lib/python3.10/site-packages/datasets/formatting/formatting.py", line 590, in query_table
    _check_valid_column_key(key, table.column_names)
  File "/home/changye/miniconda3/envs/ML/lib/python3.10/site-packages/datasets/formatting/formatting.py", line 527, in _check_valid_column_key
    raise KeyError(f"Column {key} not in the dataset. Current columns in the dataset: {columns}")
KeyError: "Column train not in the dataset. Current columns in the dataset: ['directory', 'filename', 'formal_text', 'casual_text']"
Traceback (most recent call last):
  File "/mnt/file2/changye/NLPFINAL/fine-tuning/main.py", line 175, in <module>
    main(args)
  File "/mnt/file2/changye/NLPFINAL/fine-tuning/main.py", line 94, in main
    tokenized_train = prepare_dataset(train_dataset, tokenizer, max_length=args.max_length)
  File "/mnt/file2/changye/NLPFINAL/fine-tuning/supervised_dataset.py", line 98, in prepare_dataset
    remove_columns=dataset['train'].column_names
  File "/home/changye/miniconda3/envs/ML/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2872, in __getitem__
    return self._getitem(key)
  File "/home/changye/miniconda3/envs/ML/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2856, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices)
  File "/home/changye/miniconda3/envs/ML/lib/python3.10/site-packages/datasets/formatting/formatting.py", line 590, in query_table
    _check_valid_column_key(key, table.column_names)
  File "/home/changye/miniconda3/envs/ML/lib/python3.10/site-packages/datasets/formatting/formatting.py", line 527, in _check_valid_column_key
    raise KeyError(f"Column {key} not in the dataset. Current columns in the dataset: {columns}")
KeyError: "Column train not in the dataset. Current columns in the dataset: ['directory', 'filename', 'formal_text', 'casual_text']"
