2024-12-21 23:03:47,457 INFO    MainThread:3631658 [wandb_setup.py:_flush():68] Current SDK version is 0.19.0
2024-12-21 23:03:47,457 INFO    MainThread:3631658 [wandb_setup.py:_flush():68] Configure stats pid to 3631658
2024-12-21 23:03:47,457 INFO    MainThread:3631658 [wandb_setup.py:_flush():68] Loading settings from /home/changye/.config/wandb/settings
2024-12-21 23:03:47,457 INFO    MainThread:3631658 [wandb_setup.py:_flush():68] Loading settings from /mnt/file2/changye/NLPFINAL/fine-tuning/wandb/settings
2024-12-21 23:03:47,457 INFO    MainThread:3631658 [wandb_setup.py:_flush():68] Loading settings from environment variables
2024-12-21 23:03:47,457 INFO    MainThread:3631658 [wandb_init.py:_log_setup():528] Logging user logs to /mnt/file2/changye/NLPFINAL/fine-tuning/wandb/run-20241221_230347-otmqabsj/logs/debug.log
2024-12-21 23:03:47,457 INFO    MainThread:3631658 [wandb_init.py:_log_setup():529] Logging internal logs to /mnt/file2/changye/NLPFINAL/fine-tuning/wandb/run-20241221_230347-otmqabsj/logs/debug-internal.log
2024-12-21 23:03:47,457 INFO    MainThread:3631658 [wandb_init.py:init():639] calling init triggers
2024-12-21 23:03:47,457 INFO    MainThread:3631658 [wandb_init.py:init():645] wandb.init called with sweep_config: {}
config: {'train_file': '/mnt/file2/changye/dataset/casual_formal_pair_ACL40k/val', 'val_file': '/mnt/file2/changye/dataset/casual_formal_pair_ACL40k/train', 'output_dir': '/mnt/file2/changye/model/gpt2-formal-finetuned', 'logging_dir': './logs', 'num_epochs': 3, 'train_batch_size': 8, 'eval_batch_size': 8, 'logging_steps': 100, 'max_length': 512, 'dataloader_num_workers': 60, 'gradient_accumulation_steps': 4, 'wandb_project': 'academic_finetuning', 'wandb_entity': 'academic_finetuning'}
2024-12-21 23:03:47,457 INFO    MainThread:3631658 [wandb_init.py:init():688] starting backend
2024-12-21 23:03:47,457 INFO    MainThread:3631658 [wandb_init.py:init():692] sending inform_init request
2024-12-21 23:03:47,468 INFO    MainThread:3631658 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-21 23:03:47,469 INFO    MainThread:3631658 [wandb_init.py:init():705] backend started and connected
2024-12-21 23:03:47,471 INFO    MainThread:3631658 [wandb_init.py:init():798] updated telemetry
2024-12-21 23:03:47,480 INFO    MainThread:3631658 [wandb_init.py:init():830] communicating run to backend with 90.0 second timeout
2024-12-21 23:03:48,520 ERROR   MainThread:3631658 [wandb_init.py:init():857] encountered error: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity academic_finetuning not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-12-21 23:03:48,520 ERROR   MainThread:3631658 [wandb_init.py:init():1315] error in wandb.init()
Traceback (most recent call last):
  File "/home/changye/miniconda3/envs/ML/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1305, in init
    return wi.init()
  File "/home/changye/miniconda3/envs/ML/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 863, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity academic_finetuning not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-12-21 23:03:48,530 WARNING MsgRouterThr:3631658 [router.py:message_loop():75] message_loop has been closed
